import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

export async function seedDatabase() {
  console.log('Starting RAYFLOW Database Seed with 40+ Products...');

  // 0. Ensure schema columns exist in PostgreSQL by executing single statements
  try {
    await prisma.$executeRawUnsafe(
      `ALTER TABLE "Merchant" ADD COLUMN IF NOT EXISTS "isDemo" BOOLEAN NOT NULL DEFAULT false;`
    );
    await prisma.$executeRawUnsafe(
      `ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "passwordHash" TEXT;`
    );
    await prisma.$executeRawUnsafe(
      `ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "isDemo" BOOLEAN NOT NULL DEFAULT false;`
    );
  } catch (err) {
    console.warn('Schema sync notice:', err);
  }

  const demoMerchantIds = ['mch_aura_982', 'mch_zenith_101'];
  const demoOrders = await prisma.order.findMany({
    where: { merchantId: { in: demoMerchantIds } },
    select: { id: true },
  });
  const demoOrderIds = demoOrders.map((o) => o.id);

  // Clean demo-specific records in correct relation order so real non-demo merchants are untouched
  await prisma.webhookEvent.deleteMany({ where: { merchantId: { in: demoMerchantIds } } });
  await prisma.auditLog.deleteMany({ where: { merchantId: { in: demoMerchantIds } } });
  await prisma.payment.deleteMany({ where: { merchantId: { in: demoMerchantIds } } });
  if (demoOrderIds.length > 0) {
    await prisma.orderItem.deleteMany({ where: { orderId: { in: demoOrderIds } } });
  }
  await prisma.order.deleteMany({ where: { merchantId: { in: demoMerchantIds } } });
  await prisma.campaign.deleteMany({ where: { merchantId: { in: demoMerchantIds } } });
  await prisma.revenueOpportunity.deleteMany({ where: { merchantId: { in: demoMerchantIds } } });
  await prisma.customer.deleteMany({ where: { merchantId: { in: demoMerchantIds } } });
  await prisma.product.deleteMany({ where: { merchantId: { in: demoMerchantIds } } });
  await prisma.agentPolicy.deleteMany({ where: { merchantId: { in: demoMerchantIds } } });
  await prisma.user.deleteMany({ where: { merchantId: { in: demoMerchantIds } } });
  await prisma.merchant.deleteMany({ where: { id: { in: demoMerchantIds } } });

  // 1. Create Primary Merchant: Aura Athletics
  const passwordHash = await bcrypt.hash('demo123', 10);
  const auraMerchant = await prisma.merchant.create({
    data: {
      id: 'mch_aura_982',
      name: 'Aura Athletics',
      slug: 'aura-athletics',
      email: 'arjun@auraathletics.com',
      isDemo: true,
      users: {
        create: [
          {
            id: 'usr_arjun_982',
            name: 'Arjun Sharma',
            email: 'arjun@auraathletics.com',
            passwordHash,
            role: 'MERCHANT_ADMIN',
          },
          {
            id: 'usr_pooja_982',
            name: 'Pooja Nair',
            email: 'pooja@auraathletics.com',
            passwordHash,
            role: 'MERCHANT_MEMBER',
          },
        ],
      },
      policy: {
        create: {
          maxDiscountPercent: 20.0,
          maxCampaignBudget: 50000.0,
          maxSingleTransaction: 25000.0,
          approvalThresholdDiscount: 15.0,
          approvalThresholdCampaign: 15000.0,
        },
      },
    },
  });

  // 2. Create Secondary Merchant for Multi-Tenancy Testing
  const zenithPasswordHash = await bcrypt.hash('zenith123', 10);
  const zenithMerchant = await prisma.merchant.create({
    data: {
      id: 'mch_zenith_101',
      name: 'Zenith Active',
      slug: 'zenith-active',
      email: 'rohan@zenithactive.com',
      isDemo: true,
      users: {
        create: [
          {
            id: 'usr_rohan_101',
            name: 'Rohan Varma',
            email: 'rohan@zenithactive.com',
            passwordHash: zenithPasswordHash,
            role: 'MERCHANT_ADMIN',
          },
        ],
      },
      policy: {
        create: {
          maxDiscountPercent: 18.0,
          maxCampaignBudget: 40000.0,
          maxSingleTransaction: 20000.0,
          approvalThresholdDiscount: 12.0,
          approvalThresholdCampaign: 10000.0,
        },
      },
    },
  });

  // 3. Seed 40+ Products for Aura Athletics
  const productsData = [
    // --- FOOTWEAR (8 Products) ---
    {
      id: 'prod_velocity_runner',
      name: 'Velocity Runner Pro',
      sku: 'AA-SHOE-001',
      description: 'High-cushion carbon-plated marathon shoe designed for long distance tempo runs.',
      price: 4999.0,
      compareAtPrice: 5999.0,
      category: 'Footwear',
      inventory: 48,
      conversionRate: 4.2,
      marginPercent: 64.0,
      image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_performance_socks', 'prod_hydration_bottle', 'prod_running_cap']),
    },
    {
      id: 'prod_tempo_fly_shoe',
      name: 'TempoFly Carbon Racer',
      sku: 'AA-SHOE-002',
      description: 'Ultralight race day shoe with responsive PEBA foam and full carbon fiber plate.',
      price: 5499.0,
      compareAtPrice: 6499.0,
      category: 'Footwear',
      inventory: 35,
      conversionRate: 3.9,
      marginPercent: 60.0,
      image: 'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_performance_socks', 'prod_electrolyte_tabs']),
    },
    {
      id: 'prod_trail_blazer_shoe',
      name: 'TrailBlazer Waterproof Shoe',
      sku: 'AA-SHOE-003',
      description: 'Rugged all-terrain trail shoe with Vibram rubber lugs and waterproof upper.',
      price: 4299.0,
      compareAtPrice: 4999.0,
      category: 'Footwear',
      inventory: 42,
      conversionRate: 3.5,
      marginPercent: 65.0,
      image: 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_running_backpack', 'prod_hydration_bottle']),
    },
    {
      id: 'prod_cloud_glide_shoe',
      name: 'CloudGlide Daily Trainer',
      sku: 'AA-SHOE-004',
      description: 'Plush daily training shoe with max cushioning for easy recovery mileage.',
      price: 3899.0,
      compareAtPrice: 4499.0,
      category: 'Footwear',
      inventory: 60,
      conversionRate: 4.8,
      marginPercent: 68.0,
      image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_performance_socks']),
    },
    {
      id: 'prod_stride_max_shoe',
      name: 'StrideMax Cushioned Shoe',
      sku: 'AA-SHOE-005',
      description: 'Stable guidance trainer featuring dual-density arch support for overpronators.',
      price: 4199.0,
      compareAtPrice: 4899.0,
      category: 'Footwear',
      inventory: 30,
      conversionRate: 3.2,
      marginPercent: 62.0,
      image: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_compression_sleeves']),
    },
    {
      id: 'prod_sprint_zero_spike',
      name: 'SprintZero Track Spikes',
      sku: 'AA-SHOE-006',
      description: 'Pebax spike plate track shoe engineered for 100m to 400m sprint events.',
      price: 3299.0,
      compareAtPrice: 3999.0,
      category: 'Footwear',
      inventory: 22,
      conversionRate: 2.8,
      marginPercent: 58.0,
      image: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_sweatband_headband']),
    },
    {
      id: 'prod_recovery_slide_sandal',
      name: 'Post-Run Recovery Slides',
      sku: 'AA-SHOE-007',
      description: 'Oversized EVA foam arch-support recovery slides for post-workout foot relief.',
      price: 1499.0,
      compareAtPrice: 1999.0,
      category: 'Footwear',
      inventory: 85,
      conversionRate: 5.9,
      marginPercent: 75.0,
      image: 'https://images.unsplash.com/photo-1603808033192-082d6919d3e1?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_foam_roller']),
    },
    {
      id: 'prod_barefoot_flex_shoe',
      name: 'BarefootFlex Minimalist Shoe',
      sku: 'AA-SHOE-008',
      description: 'Zero-drop wide toe box trainer for natural foot strengthening and gym workouts.',
      price: 2999.0,
      compareAtPrice: 3599.0,
      category: 'Footwear',
      inventory: 40,
      conversionRate: 3.6,
      marginPercent: 66.0,
      image: 'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_lacrosse_massage_ball']),
    },

    // --- APPAREL (10 Products) ---
    {
      id: 'prod_running_jacket',
      name: 'StormShield Windbreaker Jacket',
      sku: 'AA-APP-001',
      description: 'Water-repellent featherweight packable running jacket with 360-degree reflectivity.',
      price: 4299.0,
      compareAtPrice: 5299.0,
      category: 'Apparel',
      inventory: 25,
      conversionRate: 3.1,
      marginPercent: 62.0,
      image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_velocity_runner']),
    },
    {
      id: 'prod_dryfit_tee_mens',
      name: 'ProFit Moisture-Wicking Tee',
      sku: 'AA-APP-002',
      description: 'Ultra-soft anti-odor running shirt with micro-perforated back ventilation.',
      price: 999.0,
      compareAtPrice: 1299.0,
      category: 'Apparel',
      inventory: 140,
      conversionRate: 6.2,
      marginPercent: 72.0,
      image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_marathon_shorts']),
    },
    {
      id: 'prod_compression_tights',
      name: 'CoreFlex Compression Tights',
      sku: 'AA-APP-003',
      description: 'Targeted muscle support tights with bounce-proof phone pockets and flatlock seams.',
      price: 1899.0,
      compareAtPrice: 2299.0,
      category: 'Apparel',
      inventory: 70,
      conversionRate: 4.5,
      marginPercent: 68.0,
      image: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_velocity_runner']),
    },
    {
      id: 'prod_marathon_shorts',
      name: 'UltraVent 2-in-1 Running Shorts',
      sku: 'AA-APP-004',
      description: 'Lightweight outer shell with built-in compression liner and gel loops.',
      price: 1299.0,
      compareAtPrice: 1599.0,
      category: 'Apparel',
      inventory: 110,
      conversionRate: 5.4,
      marginPercent: 70.0,
      image: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_dryfit_tee_mens']),
    },
    {
      id: 'prod_seamless_crop_top',
      name: 'Aeroflow Seamless Crop Top',
      sku: 'AA-APP-005',
      description: 'Breathable 4-way stretch active crop top engineered for zero friction.',
      price: 1199.0,
      compareAtPrice: 1499.0,
      category: 'Apparel',
      inventory: 80,
      conversionRate: 4.9,
      marginPercent: 73.0,
      image: 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_sweat_resistant_bra']),
    },
    {
      id: 'prod_thermal_fleece_hoodie',
      name: 'ThermoRun Fleece Hoodie',
      sku: 'AA-APP-006',
      description: 'Thermal grid fleece pullover hoodie with fold-over mitten cuffs for cold runs.',
      price: 2799.0,
      compareAtPrice: 3299.0,
      category: 'Apparel',
      inventory: 45,
      conversionRate: 3.4,
      marginPercent: 64.0,
      image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_running_cap']),
    },
    {
      id: 'prod_reflective_vest',
      name: 'High-Vis Night Run Vest',
      sku: 'AA-APP-007',
      description: 'Fluorescent LED-compatible safety vest with high-reflectivity glass bead bands.',
      price: 899.0,
      compareAtPrice: 1199.0,
      category: 'Apparel',
      inventory: 65,
      conversionRate: 4.1,
      marginPercent: 74.0,
      image: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_running_cap']),
    },
    {
      id: 'prod_sweat_resistant_bra',
      name: 'ImpactSupport Sports Bra',
      sku: 'AA-APP-008',
      description: 'High-impact molded cup sports bra with adjustable cross-back racerback straps.',
      price: 1499.0,
      compareAtPrice: 1899.0,
      category: 'Apparel',
      inventory: 90,
      conversionRate: 5.2,
      marginPercent: 71.0,
      image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_seamless_crop_top']),
    },
    {
      id: 'prod_merino_wool_base',
      name: 'Merino Thermal Base Layer',
      sku: 'AA-APP-009',
      description: '100% natural Merino wool long sleeve shirt for natural thermoregulation.',
      price: 2299.0,
      compareAtPrice: 2799.0,
      category: 'Apparel',
      inventory: 35,
      conversionRate: 3.0,
      marginPercent: 61.0,
      image: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_thermal_fleece_hoodie']),
    },
    {
      id: 'prod_lightweight_singlet',
      name: 'RaceDay Mesh Singlet',
      sku: 'AA-APP-010',
      description: 'Featherweight competition singlet with bonded seams and zero restriction fit.',
      price: 799.0,
      compareAtPrice: 999.0,
      category: 'Apparel',
      inventory: 120,
      conversionRate: 6.0,
      marginPercent: 76.0,
      image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_marathon_shorts']),
    },

    // --- HYDRATION (6 Products) ---
    {
      id: 'prod_hydration_bottle',
      name: 'Ergo Grip Hydration Flask (750ml)',
      sku: 'AA-BTL-001',
      description: 'BPA-free squeezable handheld running water bottle with leak-proof jet valve.',
      price: 799.0,
      compareAtPrice: 999.0,
      category: 'Hydration',
      inventory: 95,
      conversionRate: 5.1,
      marginPercent: 72.0,
      image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_velocity_runner']),
    },
    {
      id: 'prod_insulated_steel_bottle',
      name: 'IceChill Stainless Bottle (1000ml)',
      sku: 'AA-BTL-002',
      description: 'Vacuum-insulated double-wall thermal bottle keeping liquids cold for 24 hours.',
      price: 1499.0,
      compareAtPrice: 1799.0,
      category: 'Hydration',
      inventory: 75,
      conversionRate: 4.7,
      marginPercent: 69.0,
      image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_electrolyte_tabs']),
    },
    {
      id: 'prod_soft_flask_pair',
      name: 'SoftHydrate 500ml Flask Pair',
      sku: 'AA-BTL-003',
      description: 'Flexible collapsible TPU soft flasks designed for trail running vest pockets.',
      price: 999.0,
      compareAtPrice: 1299.0,
      category: 'Hydration',
      inventory: 110,
      conversionRate: 5.8,
      marginPercent: 74.0,
      image: 'https://images.unsplash.com/photo-1523362628745-0c100150b504?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_running_backpack']),
    },
    {
      id: 'prod_handheld_run_bottle',
      name: 'QuickSip Handheld Bottle (350ml)',
      sku: 'AA-BTL-004',
      description: 'Adjustable mesh hand strap bottle with key zip pocket for quick 5k/10k runs.',
      price: 599.0,
      compareAtPrice: 799.0,
      category: 'Hydration',
      inventory: 130,
      conversionRate: 6.4,
      marginPercent: 77.0,
      image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_dryfit_tee_mens']),
    },
    {
      id: 'prod_electrolyte_tabs',
      name: 'ElectroBoost Hydration Tabs (12-Pack)',
      sku: 'AA-NUT-001',
      description: 'Zero-sugar effervescent electrolyte tablets rich in sodium, potassium, and magnesium.',
      price: 449.0,
      compareAtPrice: 599.0,
      category: 'Hydration',
      inventory: 210,
      conversionRate: 7.5,
      marginPercent: 81.0,
      image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_hydration_bottle']),
    },
    {
      id: 'prod_hydration_belt',
      name: 'HydroBelt Dual Bottle Carrier',
      sku: 'AA-BTL-005',
      description: 'Ergonomic non-bounce waist pack with two 250ml flasks and touchscreen phone pouch.',
      price: 1299.0,
      compareAtPrice: 1599.0,
      category: 'Hydration',
      inventory: 50,
      conversionRate: 4.0,
      marginPercent: 67.0,
      image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_velocity_runner']),
    },

    // --- RECOVERY (7 Products) ---
    {
      id: 'prod_massage_gun',
      name: 'DeepTissue Percussion Massage Gun',
      sku: 'AA-REC-001',
      description: 'Ultra-quiet brushless 30-speed massage gun with 6 interchangeable foam heads.',
      price: 5999.0,
      compareAtPrice: 7499.0,
      category: 'Recovery',
      inventory: 28,
      conversionRate: 2.7,
      marginPercent: 52.0,
      image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_foam_roller']),
    },
    {
      id: 'prod_foam_roller',
      name: 'GridPattern High-Density Foam Roller',
      sku: 'AA-REC-002',
      description: '3D multi-density foam roller designed for deep tissue myofascial self-massage.',
      price: 1199.0,
      compareAtPrice: 1499.0,
      category: 'Recovery',
      inventory: 90,
      conversionRate: 5.3,
      marginPercent: 75.0,
      image: 'https://images.unsplash.com/photo-1600881333168-2ef49b341f30?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_recovery_slide_sandal']),
    },
    {
      id: 'prod_compression_sleeves',
      name: 'Calfflex Graduated Compression Sleeves',
      sku: 'AA-REC-003',
      description: 'Medical-grade 20-30 mmHg calf compression sleeves to reduce shin splints.',
      price: 899.0,
      compareAtPrice: 1199.0,
      category: 'Recovery',
      inventory: 115,
      conversionRate: 6.1,
      marginPercent: 78.0,
      image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_stride_max_shoe']),
    },
    {
      id: 'prod_lacrosse_massage_ball',
      name: 'Dual Trigger-Point Massage Ball',
      sku: 'AA-REC-004',
      description: 'Firm rubber peanut massage ball for plantar fasciitis and thoracic spine relief.',
      price: 399.0,
      compareAtPrice: 599.0,
      category: 'Recovery',
      inventory: 160,
      conversionRate: 7.2,
      marginPercent: 82.0,
      image: 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_barefoot_flex_shoe']),
    },
    {
      id: 'prod_ice_compression_wrap',
      name: 'ColdRelief Knee Compression Wrap',
      sku: 'AA-REC-005',
      description: 'Reusable gel cold pack wrap with pneumatic pump pressure for knee swelling.',
      price: 1299.0,
      compareAtPrice: 1699.0,
      category: 'Recovery',
      inventory: 45,
      conversionRate: 3.9,
      marginPercent: 67.0,
      image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_massage_gun']),
    },
    {
      id: 'prod_stretching_strap',
      name: 'FlexAssist Mobility Stretch Strap',
      sku: 'AA-REC-006',
      description: 'Multi-loop non-elastic stretching band for hamstring and IT band mobility.',
      price: 499.0,
      compareAtPrice: 699.0,
      category: 'Recovery',
      inventory: 130,
      conversionRate: 6.5,
      marginPercent: 79.0,
      image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_foam_roller']),
    },
    {
      id: 'prod_muscle_rub_balm',
      name: 'ActiveEase Plant Herbal Muscle Balm',
      sku: 'AA-REC-007',
      description: 'Cooling menthol and arnica topical salve for post-workout muscle soreness.',
      price: 699.0,
      compareAtPrice: 899.0,
      category: 'Recovery',
      inventory: 140,
      conversionRate: 6.8,
      marginPercent: 77.0,
      image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_foam_roller']),
    },

    // --- FITNESS TECH (5 Products) ---
    {
      id: 'prod_fitness_band',
      name: 'PulseTrack GPS Cardio Band',
      sku: 'AA-TECH-001',
      description: 'Optic heart-rate & VO2 max telemetry tracker with 14-day battery life.',
      price: 3499.0,
      compareAtPrice: 4499.0,
      category: 'Tech',
      inventory: 32,
      conversionRate: 2.9,
      marginPercent: 55.0,
      image: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_velocity_runner']),
    },
    {
      id: 'prod_bone_conduction_headphones',
      name: 'AeroSport Bone Conduction Earbuds',
      sku: 'AA-TECH-002',
      description: 'Open-ear bone conduction Bluetooth headset for ambient outdoor running safety.',
      price: 4999.0,
      compareAtPrice: 5999.0,
      category: 'Tech',
      inventory: 24,
      conversionRate: 3.3,
      marginPercent: 58.0,
      image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_fitness_band']),
    },
    {
      id: 'prod_chest_strap_hr',
      name: 'Precision Pulse Heart Rate Chest Strap',
      sku: 'AA-TECH-003',
      description: 'Dual ANT+ and Bluetooth LE ECG chest monitor with real-time HRV transmission.',
      price: 2199.0,
      compareAtPrice: 2699.0,
      category: 'Tech',
      inventory: 50,
      conversionRate: 4.1,
      marginPercent: 65.0,
      image: 'https://images.unsplash.com/photo-1510017803434-a899398421b3?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_fitness_band']),
    },
    {
      id: 'prod_smart_jump_rope',
      name: 'SpeedCount Bluetooth Smart Jump Rope',
      sku: 'AA-TECH-004',
      description: 'Steel core tangle-free jump rope with LED display handle and revolution counter.',
      price: 1299.0,
      compareAtPrice: 1599.0,
      category: 'Tech',
      inventory: 85,
      conversionRate: 5.6,
      marginPercent: 71.0,
      image: 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_barefoot_flex_shoe']),
    },
    {
      id: 'prod_clip_on_run_pod',
      name: 'CadenceTrack Running Dynamics Pod',
      sku: 'AA-TECH-005',
      description: 'Shoe-mounted sensor computing stride frequency, ground contact time, and vertical oscillation.',
      price: 1899.0,
      compareAtPrice: 2299.0,
      category: 'Tech',
      inventory: 40,
      conversionRate: 3.7,
      marginPercent: 63.0,
      image: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_velocity_runner']),
    },

    // --- GEAR & ACCESSORIES (7 Products) ---
    {
      id: 'prod_performance_socks',
      name: 'Performance Running Socks (3-Pack)',
      sku: 'AA-ACC-001',
      description: 'Anti-blister moisture-wicking compression socks with arch support.',
      price: 499.0,
      compareAtPrice: 699.0,
      category: 'Gear',
      inventory: 180,
      conversionRate: 6.8,
      marginPercent: 78.0,
      image: 'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_velocity_runner']),
    },
    {
      id: 'prod_running_cap',
      name: 'Aerolite UV Running Cap',
      sku: 'AA-ACC-002',
      description: 'Ultralight UPF 50+ quick-dry sun protection cap with laser-cut ventilation.',
      price: 999.0,
      compareAtPrice: 1299.0,
      category: 'Gear',
      inventory: 64,
      conversionRate: 3.8,
      marginPercent: 70.0,
      image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_velocity_runner']),
    },
    {
      id: 'prod_running_backpack',
      name: 'UltraTrail 12L Vest Backpack',
      sku: 'AA-ACC-003',
      description: 'Ergonomic bounce-free trail running vest with twin front flask holsters.',
      price: 3899.0,
      compareAtPrice: 4899.0,
      category: 'Gear',
      inventory: 19,
      conversionRate: 2.4,
      marginPercent: 58.0,
      image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_hydration_bottle']),
    },
    {
      id: 'prod_running_belt',
      name: 'SlimFit Zipper Waist Pouch',
      sku: 'AA-ACC-004',
      description: 'Expandable weather-resistant running belt for smartphone, cards, and keys.',
      price: 699.0,
      compareAtPrice: 899.0,
      category: 'Gear',
      inventory: 150,
      conversionRate: 6.9,
      marginPercent: 80.0,
      image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_cloud_glide_shoe']),
    },
    {
      id: 'prod_sweatband_headband',
      name: 'SweatLock Dri-Fit Headband',
      sku: 'AA-ACC-005',
      description: 'Non-slip silicone grip sweatband to keep perspiration out of your eyes.',
      price: 349.0,
      compareAtPrice: 499.0,
      category: 'Gear',
      inventory: 200,
      conversionRate: 7.8,
      marginPercent: 83.0,
      image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_dryfit_tee_mens']),
    },
    {
      id: 'prod_race_bib_magnets',
      name: 'Magnetic Race Bib Fasteners',
      sku: 'AA-ACC-006',
      description: 'Reusable neodymium magnet clips to attach marathon race numbers without safety pins.',
      price: 399.0,
      compareAtPrice: 599.0,
      category: 'Gear',
      inventory: 175,
      conversionRate: 7.1,
      marginPercent: 84.0,
      image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_lightweight_singlet']),
    },
    {
      id: 'prod_duffel_gym_bag',
      name: 'EnduraVent 40L Gym Duffel Bag',
      sku: 'AA-ACC-007',
      description: 'Durable water-resistant gym bag with separate ventilated shoe compartment.',
      price: 2499.0,
      compareAtPrice: 2999.0,
      category: 'Gear',
      inventory: 40,
      conversionRate: 4.3,
      marginPercent: 66.0,
      image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80',
      complementaryProductIds: JSON.stringify(['prod_recovery_slide_sandal']),
    },
  ];

  for (const item of productsData) {
    await prisma.product.create({
      data: {
        ...item,
        merchantId: auraMerchant.id,
      },
    });
  }

  // Seed isolated product for Zenith Active
  await prisma.product.create({
    data: {
      id: 'prod_zenith_yoga_mat',
      merchantId: zenithMerchant.id,
      name: 'Zenith Eco Yoga Mat',
      sku: 'ZA-MAT-001',
      description: 'Natural tree rubber alignment mat.',
      price: 2499.0,
      category: 'Tech',
      inventory: 50,
      conversionRate: 5.0,
      marginPercent: 70.0,
      image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&w=600&q=80',
    },
  });

  // 4. Create Customers for Aura Athletics
  const customerPasswordHash = await bcrypt.hash('demo123', 10);

  const customerList = [
    {
      id: 'cust_rahul_01',
      name: 'Rahul Mehta',
      email: 'rahul.mehta@example.com',
      phone: '+919820144521',
      cohort: 'Marathon Runners',
      lifetimeValue: 14850.0,
      orderCount: 3,
      intentScore: 92,
      cartStatus: 'CHECKOUT_VIEWED',
      notes: 'Viewed Velocity Runner 4x in last 24h. Candidate for 15% socks bundle.',
    },
    {
      id: 'cust_priya_02',
      name: 'Priya Sharma',
      email: 'priya@auraathletics.com',
      phone: '+919811234567',
      cohort: 'Tech Fitness Enthusiasts',
      lifetimeValue: 8499.0,
      orderCount: 2,
      intentScore: 84,
      cartStatus: 'ACTIVE',
      notes: 'Added GPS Cardio band. High affinity with hydration flask.',
    },
    {
      id: 'cust_vikram_03',
      name: 'Vikram Patel',
      email: 'vikram.patel@example.com',
      phone: '+919899887766',
      cohort: 'Weekend Runners',
      lifetimeValue: 4999.0,
      orderCount: 1,
      intentScore: 78,
      cartStatus: 'ABANDONED',
      notes: 'Abandoned checkout on StormShield Jacket. Ready for 10% recovery offer.',
    },
    {
      id: 'cust_ananya_04',
      name: 'Ananya Iyer',
      email: 'ananya.iyer@example.com',
      phone: '+919711223344',
      cohort: 'VIP Club',
      lifetimeValue: 24500.0,
      orderCount: 5,
      intentScore: 88,
      cartStatus: 'ACTIVE',
      notes: 'Top tier VIP member. High response rate to early gear drops.',
    },
    {
      id: 'cust_sameer_05',
      name: 'Sameer Joshi',
      email: 'sameer.joshi@example.com',
      phone: '+919655443322',
      cohort: 'New Store Visitors',
      lifetimeValue: 0.0,
      orderCount: 0,
      intentScore: 45,
      cartStatus: 'EMPTY',
      notes: 'First time visitor exploring footwear catalogue.',
    },
    {
      id: 'cust_neha_06',
      name: 'Neha Gupta',
      email: 'neha.gupta@example.com',
      phone: '+919876543210',
      cohort: 'Trail Runners',
      lifetimeValue: 6200.0,
      orderCount: 2,
      intentScore: 80,
      cartStatus: 'ACTIVE',
      notes: 'Interested in outdoor gear and backpack bundles.',
    },
    {
      id: 'cust_rohit_07',
      name: 'Rohit Varma',
      email: 'rohit.varma@example.com',
      phone: '+919812345678',
      cohort: 'Gym & Cross-Training',
      lifetimeValue: 3900.0,
      orderCount: 1,
      intentScore: 72,
      cartStatus: 'EMPTY',
      notes: 'Purchased recovery slides and massage ball.',
    },
    {
      id: 'cust_kavita_08',
      name: 'Kavita Singh',
      email: 'kavita.singh@example.com',
      phone: '+919823456789',
      cohort: 'Marathon Runners',
      lifetimeValue: 11200.0,
      orderCount: 3,
      intentScore: 86,
      cartStatus: 'CHECKOUT_VIEWED',
      notes: 'Regular race participant looking for hydration flask deals.',
    },
  ];

  const createdCustomers: Record<string, any> = {};
  for (const cust of customerList) {
    const c = await prisma.customer.create({
      data: {
        ...cust,
        merchantId: auraMerchant.id,
        passwordHash: customerPasswordHash,
        isDemo: true,
        lastPurchaseDate: new Date(Date.now() - Math.floor(Math.random() * 20 * 24 * 3600 * 1000)),
      },
    });
    createdCustomers[cust.id] = c;
  }

  // 5. Seed Revenue Opportunities for Aura Athletics
  const opportunitiesData = [
    {
      id: 'opp_01',
      title: 'Velocity Runner + Socks Bundle',
      subtitle: '127 shoppers viewed Velocity Runner without accessories',
      description: 'Shoppers who view Velocity Runner have a 64% co-purchase affinity for Performance Socks when offered a 15% bundle discount.',
      type: 'UPSELL',
      recommendedAction: 'Attach 15% discount for Performance Socks on Velocity Runner checkout (Save ₹200).',
      reasoning: 'Co-purchase affinity score is 0.64. Gross margin on socks is 78%, preserving net bundle margin.',
      expectedRevenue: 63400.0,
      confidence: 94,
      riskLevel: 'LOW',
      affectedCustomerCohort: 'Marathon Runners (127 shoppers)',
      affectedCustomersCount: 127,
      status: 'PENDING',
      actionPayload: JSON.stringify({ primaryProductId: 'prod_velocity_runner', addonProductId: 'prod_performance_socks', discountPercent: 15, maxBudget: 8000 }),
      policyNotes: 'Proposed discount 15% complies with 20% merchant discount cap.',
    },
    {
      id: 'opp_02',
      title: 'StormShield Jacket Cart Recovery',
      subtitle: '43 shoppers abandoned cart at payment step',
      description: '43 users added StormShield Jacket but abandoned at gateway. Automated 10% recovery offer converts 38% based on historical data.',
      type: 'ABANDONED_CHECKOUT',
      recommendedAction: 'Send 10% recovery checkout link via Razorpay Payment Link API.',
      reasoning: 'Historical recovery conversion on this cohort is 38.2%. Recovers approx ₹48,200 in gross sales.',
      expectedRevenue: 48200.0,
      confidence: 91,
      riskLevel: 'LOW',
      affectedCustomerCohort: 'Checkout Drop-offs (43 shoppers)',
      affectedCustomersCount: 43,
      status: 'PENDING',
      actionPayload: JSON.stringify({ productId: 'prod_running_jacket', discountPercent: 10, maxBudget: 5000 }),
      policyNotes: '10% discount is well within 20% threshold. Auto-approvable.',
    },
    {
      id: 'opp_03',
      title: 'GPS Cardio Band + Hydration Flask Cross-Sell',
      subtitle: 'Post-purchase sequence for 89 PulseTrack buyers',
      description: 'PulseTrack buyers show high interest in hydration gear within 14 days of purchase.',
      type: 'CROSS_SELL',
      recommendedAction: 'Trigger recommendation for Ergo Grip Bottle at ₹699 (₹100 off).',
      reasoning: '89 recent buyers identified. 34% estimated conversion rate.',
      expectedRevenue: 28500.0,
      confidence: 88,
      riskLevel: 'LOW',
      affectedCustomerCohort: 'Tech Fitness Enthusiasts (89 buyers)',
      affectedCustomersCount: 89,
      status: 'PENDING',
      actionPayload: JSON.stringify({ productId: 'prod_hydration_bottle', discountPercent: 12, maxBudget: 3500 }),
      policyNotes: 'Complies with merchant policy rules.',
    },
    {
      id: 'opp_04',
      title: 'UltraTrail Backpack Conversion Boost',
      subtitle: '450 weekly visitors with high bounce rate',
      description: 'The UltraTrail Backpack receives high views but lower conversion. Pairing with Hydration Flask boosts checkout intent.',
      type: 'LOW_CONVERSION_RECOVERY',
      recommendedAction: 'Bundle Backpack + Flask with ₹400 instant savings.',
      reasoning: 'Increases order value while clearing inventory.',
      expectedRevenue: 34800.0,
      confidence: 86,
      riskLevel: 'LOW',
      affectedCustomerCohort: 'Trail Runners (450 weekly visitors)',
      affectedCustomersCount: 450,
      status: 'PENDING',
      actionPayload: JSON.stringify({ primaryProductId: 'prod_running_backpack', addonProductId: 'prod_hydration_bottle', discountPercent: 14, maxBudget: 6000 }),
      policyNotes: '14% bundle discount is within safety limits.',
    },
    {
      id: 'opp_05',
      title: 'Aerolite UV Cap Summer Offer',
      subtitle: '180 VIP members due for re-engagement',
      description: 'Seasonal demand for sun protection running accessories.',
      type: 'UPSELL',
      recommendedAction: 'Deploy 12% member discount on Aerolite UV Cap.',
      reasoning: 'High customer loyalty cohort with strong re-order history.',
      expectedRevenue: 21600.0,
      confidence: 89,
      riskLevel: 'LOW',
      affectedCustomerCohort: 'VIP Club (180 members)',
      affectedCustomersCount: 180,
      status: 'PENDING',
      actionPayload: JSON.stringify({ productId: 'prod_running_cap', discountPercent: 12, maxBudget: 4000 }),
      policyNotes: 'Within policy limit.',
    },
  ];

  for (const opp of opportunitiesData) {
    await prisma.revenueOpportunity.create({
      data: {
        ...opp,
        merchantId: auraMerchant.id,
      },
    });
  }

  // 6. Seed Campaigns for Aura Athletics
  await prisma.campaign.create({
    data: {
      id: 'camp_01',
      merchantId: auraMerchant.id,
      name: 'Spring Marathon Prep',
      targetCohort: 'Customers who viewed marathon shoes in last 60 days',
      discountPercent: 15.0,
      maxBudget: 25000.0,
      estimatedAudience: 2430,
      expectedRevenue: 98500.0,
      convertedOrders: 18,
      status: 'ACTIVE',
      aiReasoning: 'Targets marathoners with 15% accessories bundle.',
    },
  });

  // 7. Seed Orders & Payments for Aura Athletics
  const c1 = createdCustomers['cust_rahul_01'];
  const o1 = await prisma.order.create({
    data: {
      id: 'ord_01',
      merchantId: auraMerchant.id,
      orderNumber: 'ORD-2026-9901',
      razorpayOrderId: 'order_RAYFlow_9901_test',
      razorpayPaymentId: 'pay_RAYFlow_9901_test',
      customerId: c1.id,
      customerName: c1.name,
      customerEmail: c1.email,
      customerPhone: c1.phone,
      subtotalAmount: 5498.0,
      discountAmount: 200.0,
      totalAmount: 5298.0,
      status: 'PAID',
      paymentMethod: 'upi',
      isBundle: true,
      bundleSavings: 200.0,
      items: {
        create: [
          { productId: 'prod_velocity_runner', productName: 'Velocity Runner Pro', quantity: 1, unitPrice: 4999.0, totalAmount: 4999.0 },
          { productId: 'prod_performance_socks', productName: 'Performance Running Socks (3-Pack)', quantity: 1, unitPrice: 499.0, totalAmount: 499.0 },
        ],
      },
      payments: {
        create: {
          merchantId: auraMerchant.id,
          razorpayPaymentId: 'pay_RAYFlow_9901_test',
          razorpayOrderId: 'order_RAYFlow_9901_test',
          amount: 5298.0,
          currency: 'INR',
          status: 'CAPTURED',
          method: 'upi',
          email: c1.email,
          contact: c1.phone,
          signature: 'sig_valid_test_sha256_9901',
          signatureVerified: true,
        },
      },
    },
  });

  // 8. Seed Initial Audit Logs for Aura Athletics
  await prisma.auditLog.create({
    data: {
      merchantId: auraMerchant.id,
      actorId: 'system',
      actorName: 'System',
      agentName: 'Assistant',
      actionType: 'OPPORTUNITY_CREATED',
      entityType: 'OPPORTUNITY',
      entityId: 'opp_01',
      amount: 63400.0,
      policyCheck: 'PASSED',
      approval: 'AUTO_APPROVED',
      result: 'SUCCESS',
      reason: 'Calculated 15% bundle discount for Velocity Runner + Socks under 20% cap.',
      metadata: JSON.stringify({ confidence: 94 }),
    },
  });

  await prisma.auditLog.create({
    data: {
      merchantId: auraMerchant.id,
      actorId: c1.id,
      actorName: c1.name,
      agentName: 'Assistant',
      actionType: 'ORDER_CREATED',
      entityType: 'ORDER',
      entityId: o1.id,
      amount: 5298.0,
      policyCheck: 'PASSED',
      approval: 'AUTO_APPROVED',
      result: 'SUCCESS',
      reason: 'Customer completed checkout for Velocity Runner bundle.',
      metadata: JSON.stringify({ orderNumber: o1.orderNumber, rzpOrderId: o1.razorpayOrderId }),
    },
  });

  console.log(`RAYFLOW Database successfully seeded with 43 products across 6 categories!`);
}

if (process.argv[1]?.includes('seed')) {
  seedDatabase()
    .catch((e) => {
      console.error(e);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}
